# Generated by Django 3.1.5 on 2021-01-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='{{ cookiecutter.main_model }}',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=264)),
                ('done', models.BooleanField(default=False)),
                ('due_to', models.DateTimeField()),
            ],
        ),
    ]
